[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[lib]
bench = false

[[bench]]
name = "aoc_bench"
harness = false
path = "src/bench.rs"

[dev-dependencies]
criterion = { version = "0.8" }

[dependencies]
rayon = "1.11.0"
smallvec = "1"
z3 = "0.19.6"
